spring:
  application:
    name: parser
  main:
    banner-mode: "off"    

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/log?autoReconnect=true&useSSL=false
    username: root
    password: 123456
  # jpa
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate.ddl-auto: create
    
tool:
  loadData: true
    
server:
  port: 8080
  
logging:
  config: config/log4j2-console.xml

---  
spring:
  profiles: memory
  # hsqldb  
  datasource:
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem:userdb
    username: sa
    password: sa
  # jpa
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    show-sql: false
    hibernate.ddl-auto: create-drop
    database: HSQL
# logging:
#   level:
#     org.springframework.transaction: DEBUG
#    org.springframework.orm.jpa: DEBUG     

      
      
      