spring:
  application:
    name: parser
  main:
    banner-mode: "off"    

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/log?autoReconnect=true&useSSL=false
    username: root
    password: 123456
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate.ddl-auto: none
    
tool:
  loadData: true
    
server:
  port: 8080

logging:
  pattern:
    console:  
#  config: log4j2-console.xml

      
      
      